export const PRICES_RANGE = "PRICES_RANGE";
export const FLIGHT_TIME_THERE = "FLIGHT_TIME_THERE";
export const FLIGHT_TIME_RETURN = "FLIGHT_TIME_RETURN";
export const FLIGHT_HOURS_THERE = "FLIGHT_HOURS_THERE";
export const FLIGHT_HOURS_RETURN = "FLIGHT_HOURS_RETURN";